name: Format Markdown
on:
  pull_request:
    paths:
      - "**/*.md"

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: minvws/action-markdown-formatter@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
